### ISSUE TITLE
transformer_data

### ISSUE THREAD

**Issue by duxinkang** [LaihoE/ML-AntiCheat-CSGO#2]
hi,it's good see this work in csgo,im a fan too.Could u providethe data of traning this model,or the way get all these data ,thanks in advance

**Comment by LaihoE** [comment]
Unfortunately this is the type of data you don't want floating around. For collecting demos, most server providers allow you to download demos.

**Comment by duxinkang** [comment]
Thanks.Yep,the many way can get them,but how to know the y labels,which ticks or shot is cheat?
